### ISSUE TITLE
Youtube with HTML fails in Safari - while switching playlist

### ISSUE THREAD

**Issue by tosbourn** [InnovationEnterprise/slideme-ie#19]
When trying the examples in Safari I noticed that the Youtube + HTML example just froze.

![screen shot 2015-11-11 at 17 42 14](https://cloud.githubusercontent.com/assets/456902/11098236/92fd187e-889b-11e5-83ec-7e8e9c26d03d.png)

**Comment by xoxoxo** [comment]
its not jsut about youtube but swtiching from example slideshare to yt. yt itsefl works fine
