### ISSUE TITLE
Wistia Embed Support

### ISSUE THREAD

**Issue by tosbourn** [InnovationEnterprise/slideme-ie#30]
If SlideMe could support Wistia embeds we could use it on some of our other applications.

Example embed code could be

```
<div class="wistia_responsive_padding" style="padding:56.25% 0 0 0;position:relative;"><div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;"><iframe src="//fast.wistia.net/embed/iframe/p9k93dcxj1?videoFoam=true" allowtransparency="true" frameborder="0" scrolling="no" class="wistia_embed" name="wistia_embed" allowfullscreen mozallowfullscreen webkitallowfullscreen oallowfullscreen msallowfullscreen width="100%" height="100%"></iframe></div></div>
<script src="//fast.wistia.net/assets/external/E-v1.js" async></script>
```

If there was some way we could add this into the JSON file it would be ideal. See https://github.com/InnovationEnterprise/hubs/issues/2007

**Comment by xoxoxo** [comment]
well that works perfectly fine with slideme 0.1.1 (made a pr with upgrade for channels)

only thing that we have to remember is to replace " with ' and make sure everything is in one line

example:
<div class='wistia_responsive_padding' style='padding:56.25% 0 0 0;position:relative;'><div class='wistia_responsive_wrapper' style='height:100%;left:0;position:absolute;top:0;width:100%;'><iframe src='//fast.wistia.net/embed/iframe/p9k93dcxj1?videoFoam=true' allowtransparency='true' frameborder='0' scrolling='no' class='wistia_embed' name='wistia_embed' allowfullscreen mozallowfullscreen webkitallowfullscreen oallowfullscreen msallowfullscreen width='100%' height='100%'></iframe></div></div><script src='//fast.wistia.net/assets/external/E-v1.js' async></script>
