### ISSUE TITLE
Multi-instance operation

### ISSUE THREAD

**Issue by squidster** [InnovationEnterprise/slideme-ie#37]
Sorry, this may not be a bug, but I found no samples of running multiple instances of SlideMe.
What I want to do for 3 instances:
1. Local .mp4 clip
2. Local .png/jpg image
3. YouTube clip

Any links to sample multi-configuration will be much appreciated.
Thanks!

**Comment by xoxoxo** [comment]
At the moment its very tricky/not possible but you can use a playlist option to switch between them. Ill add this a as thing to do.

**Comment by xoxoxo** [comment]
repo has been moved to https://github.com/InnovationEnterprise/let-me-slide-that-for-you. Ill have a look on that one soon.
